/** Auto-generated from /logolar. Client logos for the home marquee. */
export type BrandLogo = { src: string; alt: string };
export const BRAND_LOGOS: BrandLogo[] = [
  { src: '/logos/asli-aslan-beauty-002-beyazz.webp', alt: 'Aslı Aslan Beauty 002 beyazz' },
  { src: '/logos/bicakci-naim-logo.webp', alt: 'Bıçakçı Naim logo' },
  { src: '/logos/duzel-grp-beyaz.webp', alt: 'Düzel GRP beyaz' },
  { src: '/logos/f-a-u-s-t.webp', alt: 'F A U S T' },
  { src: '/logos/hifa.webp', alt: 'HIFA' },
  { src: '/logos/logo-beyaz-2.webp', alt: 'LOGO - BEYAZ (2)' },
  { src: '/logos/muberya-saglam-iskenderun-logo-line.webp', alt: 'Müberya Sağlam İskenderun LOGO Line' },
  { src: '/logos/nadir-firinciogullari-logo-s.webp', alt: 'Nadir Fırıncıoğulları LOGO s' },
  { src: '/logos/tedx.webp', alt: 'TEDx' },
  { src: '/logos/turuncu-motor.webp', alt: 'Turuncu Motor' },
  { src: '/logos/un-women.webp', alt: 'UN-Women' },
  { src: '/logos/aga.webp', alt: 'aga' },
  { src: '/logos/akdeniz-genclik-fest.webp', alt: 'akdeniz gençlik fest' },
  { src: '/logos/arti-turizm.webp', alt: 'artı turizm' },
  { src: '/logos/aspava.webp', alt: 'aspava' },
  { src: '/logos/ay-cicek.webp', alt: 'ay çiçek' },
  { src: '/logos/chicken-doner.webp', alt: 'chicken döner' },
  { src: '/logos/dast-logo-beyaz.webp', alt: 'dast logo beyaz' },
  { src: '/logos/dogrular-seramik-antakya.webp', alt: 'doğrular seramik antakya' },
  { src: '/logos/ekin-koleji.webp', alt: 'ekin koleji' },
  { src: '/logos/emre-gul-production.webp', alt: 'emre gül production' },
  { src: '/logos/evvell-temmuz.webp', alt: 'evvell temmuz' },
  { src: '/logos/kia-oztopraklar.webp', alt: 'kia öztopraklar' },
  { src: '/logos/lia.webp', alt: 'lia' },
  { src: '/logos/mku-logo.webp', alt: 'mkü logo' },
  { src: '/logos/paksoy-logo.webp', alt: 'paksoy logo' },
  { src: '/logos/pia-dental.webp', alt: 'pia dental' },
  { src: '/logos/renkli-dusler-anaokulu.webp', alt: 'renkli düşler anaokulu' },
  { src: '/logos/rootraft-cafe.webp', alt: 'rootraft cafe' },
  { src: '/logos/sista-butik.webp', alt: 'sista butik' },
  { src: '/logos/zeynep-loka-logo-cizim-beyaz.webp', alt: 'zeynep loka logo çizim BEYAZ' },
  { src: '/logos/sabanoglu-logo-finalss.webp', alt: 'ŞABANOĞLU_LOGO_FİNALss' },
];
