import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { isAppLocale } from '@/i18n/routing';
import { buildMetadata } from '@/lib/metadata';
import { Hero, type HeroService } from '@/components/hero/Hero';
import { ScrollHint } from '@/components/layout/ScrollHint';
import {
  ServiceCarousel,
  type CarouselCard,
} from '@/components/sections/ServiceCarousel';
import {
  ProjectsPreview,
  type ProjectItem,
} from '@/components/sections/ProjectsPreview';
import { WhyUs, type WhyItem } from '@/components/sections/WhyUs';
import { ContactCta } from '@/components/sections/ContactCta';
import { generatedServiceCards } from '@/lib/service-cards.generated';
import { PROJECT_SLIDES } from '@/lib/projects-data';
import { CONTACT } from '@/lib/contact';

// Carousel order — grouped by discipline (advertising → web → social →
// production), not alphabetical. Slugs not listed here fall to the end, so a
// newly dropped-in photo still shows until it's placed in a group.
const SERVICE_ORDER = [
  'google-seo',
  'meta-reklamlari',
  'tiktok-reklamlari',
  'youtube-reklamlari',
  'web-tasarimi',
  'web-otomasyonlari',
  'crm',
  'yapay-zeka',
  'sosyal-medya',
  'reklam-filmi',
  'video-cekimi',
  'fotograf-cekimi',
  'kisa-film',
  'reji-hizmeti',
];

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  if (!isAppLocale(locale)) return {};
  return buildMetadata({ locale, metaKey: 'home', pathname: '/' });
}

export default async function HomePage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!isAppLocale(locale)) notFound();
  setRequestLocale(locale);

  const t = await getTranslations();

  const services: HeroService[] = [
    { key: 'ads', title: t('services.ads.title'), from: 'left' },
    { key: 'web', title: t('services.web.title'), from: 'right' },
    { key: 'social', title: t('services.social.title'), from: 'left' },
    { key: 'pr', title: t('services.pr.title'), from: 'right' },
  ];

  // One image-only card per photo in "Hizmetlerimiz Kart Görselleri",
  // generated by scripts/build-service-cards, then ordered by discipline.
  const rank = (slug: string) => {
    const i = SERVICE_ORDER.indexOf(slug);
    return i === -1 ? SERVICE_ORDER.length : i;
  };
  // Only the first six on the home carousel; the rest live on /services.
  const serviceCards: CarouselCard[] = [...generatedServiceCards]
    .sort((a, b) => rank(a.slug) - rank(b.slug))
    .slice(0, 6)
    .map((c) => ({ key: c.slug, title: c.name, items: [], image: c.image }));

  const whyItems: WhyItem[] = (['w1', 'w2', 'w3', 'w4'] as const).map((key) => ({
    key,
    title: t(`home.why.items.${key}.title`),
    body: t(`home.why.items.${key}.body`),
  }));

  // A few featured projects; the rest live on /projects. Images come from the
  // shared slide list so the home preview matches the full portfolio.
  const projectItems: ProjectItem[] = PROJECT_SLIDES.slice(0, 3).map((slide) => ({
    key: slide.key,
    image: slide.image,
    title: t(`home.projects.items.${slide.key}.title`),
    meta: t(`home.projects.items.${slide.key}.meta`),
  }));

  return (
    <main>
      <Hero question={t('hero.question')} services={services} />
      <ScrollHint label={t('home.scrollHint')} />

      <ServiceCarousel
        label={t('servicesPage.label')}
        title={t('servicesPage.title')}
        cardCta={t('servicesPage.cardCta')}
        cta={t('servicesPage.carouselCta')}
        cards={serviceCards}
      />

      <ProjectsPreview
        label={t('home.projects.label')}
        title={t('home.projects.title')}
        viewAll={t('home.projects.viewAll')}
        projects={projectItems}
      />

      <WhyUs
        label={t('home.why.label')}
        title={t('home.why.title')}
        items={whyItems}
      />

      <ContactCta
        label={t('home.contact.label')}
        title={t('home.contact.title')}
        cta={t('home.contact.cta')}
        mailLabel={t('home.contact.mailLabel')}
        email={CONTACT.email}
      />
    </main>
  );
}
